### ISSUE TITLE
Desktop refreshes every second after Screenshot to Clipboard was taken, Win11 (22504) and Greenshot 1.3.219

### ISSUE THREAD

**Issue by schuettecarsten** [greenshot/greenshot#348] opened 2021-11-29 10:24 UTC
On Windows 11 Insider (latest release, 22504.1010), Greenshot 1.3.219 causes endless desktop refreshes after "Print" key was used to capture a screenshot of a selected area and copying this to the clipboard. This onyl happens when the capture is copied to the clipboard, using file output works as expected. After taking some screenshots, the tray icons start to flicker and refresh every second, the same happens to the desktop and open windows. Computer gets slower and slower on each screenshot you take...

**Comment by badabing2005** [comment] 2021-12-03 14:26
This happens to me too, but not always, I can't pin to what conditions actually trigger it (at times it is very frequent, other times it doesn't happen for days), but I know that the following process 
<img width="638" alt="image" src="https://user-images.githubusercontent.com/22603312/144617863-f32c0bd4-faa4-4eac-9baa-44de3b19f9b4.png">
starts spawning endless child processes that end up dying.
If you kill the parent wslhost process, the flickering stops.

I also experience another issue, although am not sure if it is related to windows 11 issues or 4K monitor issues.
Only sometimes, when I take a region screenshot, and select top left to bottom right, the captured region is not accurate, the top right is clipped, the only way around it when this happens is to select bottom left to top right.


Hopefully this will help identifying the root issue.

**Comment by schuettecarsten** [comment] 2021-12-03 19:22
@badabing2005 Please use Feedback Hub in Windows 11 to report this issue there. Maybe you want to add your feedback to https://aka.ms/AAd4bd8.

**Comment by badabing2005** [comment] 2021-12-06 22:19
@schuettecarsten 
Sorry Facebook is totally blocked at our residence.
Here's a screenshot of the started / killed processes when the problem happens.
![image](https://user-images.githubusercontent.com/22603312/144931699-1cc20fbf-b22f-48cb-8a8d-cf7bfbdf45b8.png)

Perhaps someone can put a link-back Facebook Hub to this thread.

**Comment by schuettecarsten** [comment] 2021-12-07 08:24
@badabing2005 Facebook? I mean the "Feedback" tool that is integrated in Windows 11.

But this here is not a Greenshot issue, as it also occurs when using Paint or other tools to copy data into the clipboard. It seems to be caused by a combination of WSL 2, Windows 11 and Docker Desktop.

**Comment by pfeigl** [comment] 2021-12-17 13:50
For anyone else running into this still existing problem: The easiest solution seems to be to fill the clipboard with some simple text again and not have image data in there. So just press ctrl+c on any text after you are done with your screenshot.

**Comment by badabing2005** [comment] 2022-01-22 13:20
> For anyone else running into this still existing problem: The easiest solution seems to be to fill the clipboard with some simple text again and not have image data in there. So just press ctrl+c on any text after you are done with your screenshot.

That doesn't always work, in fact this issue is so annoying, even getting to the task manager to kill the process is cumbersome because of all the constant refresh that is going on.


> @badabing2005 Facebook? I mean the "Feedback" tool that is integrated in Windows 11.
> 
> But this here is not a Greenshot issue, as it also occurs when using Paint or other tools to copy data into the clipboard. It seems to be caused by a combination of WSL 2, Windows 11 and Docker Desktop.

I don't use paint, I love Greenshot, and this issue has pushed me away from using it, you say it is not a Greenshot issue and it happens with other apps, so it must be a windows issue.
I switched to ShareX and haven't experienced the issue at all, whereas with Greenshot it's a constant struggle.
How do you explain that?

**Comment by pfeigl** [comment] 2022-01-22 14:57
I can confirm, that it has to be connected to docker somehow. As soon as I stop docker, I no longer have the mentioned problem.

**Comment by Lakritzator** [comment] 2022-01-22 21:54
> I don't use paint, I love Greenshot, and this issue has pushed me away from using it, you say it is not a Greenshot issue and it happens with other apps, so it must be a windows issue. I switched to ShareX and haven't experienced the issue at all, whereas with Greenshot it's a constant struggle. How do you explain that?

That the issue doesn't happen with ShareX, makes me assume it might have to do with the clipboard format used.
But I can only assume something like that, if you are using the application in a very similar way?
Do you also copy to the clipboard with ShareX?

Btw. maybe a nice fact, ShareX shared a lot of code from Greenshot.

I still didn't manage to reproduce this issue myself, I would love to know if there would be any change in behavior if you would change the Greenshot clipboard format settings in the expert tab:
<img width="340" alt="image" src="https://user-images.githubusercontent.com/708125/150656636-fe9cddd1-9bff-49f5-98bb-93c3ee52d5c1.png">
Maybe ONLY set it to PNG, or Device Independent Bitmap?

**Comment by Lakritzator** [comment] 2022-01-22 22:34
Actually after installing docker I saw the refresh issue, not as bad as people reported though.
And it helped to disable the "Device independent bitmap" checkbox, the flashing wasn't there anymore after copying the next image to the clipboard.

So please try that.

**Comment by badabing2005** [comment] 2022-01-23 02:57
Thanks, I love Greenshot too much not to try it, I will definitely give it a shot a report back.
The funny thing is that I can go for a while without experiencing it, and other times it happens on ever screen capture, and that one really is very annoying because I become unproductive.

As I'm new to ShareX, I tried to find the equivalent settings to see what format it is, and the only thing I found was this, not sure if that's the correct area.
<img width="555" alt="ShareX_33unjG1EJS" src="https://user-images.githubusercontent.com/22603312/150663011-6834c33d-d3c4-4220-ba32-bd0659483eef.png">

**Comment by badabing2005** [comment] 2022-01-24 14:12
**# Update**
Disabling `Device independent bitmap` stops causing the refresh issue
However it introduces another issue :(
I cannot paste the contents of the clipboard (example in Microsoft Teams)
As soon as I enable it back, I can paste, but then copying to clipboard brings the refresh issue immediately.

**Comment by Lakritzator** [comment] 2022-01-24 20:01
Thanks for confirming to me that it is indeed the clipboard format, I wasn't sure it was that as for me it's only very slightly flashing.

Of course there is a disadvantage of disabling that format, I wouldn't be there if there wouldn't be a use for it. 😏 

You should enable "Windows bitmap", besides PNG for Microsoft Teams.
Why I do not roll out like that? Well, I think I remember that "Windows Bitmap" doesn't have transparency, so you will loose any support for that. For now not really an issue, as I do not support the rounded edges yet, but as soon as this works (again, see Windows 7) the image you capture of a Window has transparency in the corners. This will not be there when you paste via "Windows Bitmap".

In fact, the Windows Clipboard is 💩 
You can have one "thing" on the clipboard, but this can be in many formats.
Different applications support different formats, and take different priority (if PNG is there, application X takes it and ignores DIBV5. Application Y takes DIBV5 but ignores PNG etc.).
If Greenshot would put all possible formats on the clipboard, many apps would take the wrong format.
There is practically no right way of doing it, there is always an application not wanting it like that.

Anyway, now I know what the causes the issue, I have a bit more I could do or even tell Microsoft
I will check if the Device Independent Bitmap is properly formatted, although other applications have the same issue, maybe it does have some value somewhere which causes the issue, but is not needed or can be different... I think little chances though, and most likely Microsoft should fix it.

**Comment by Lakritzator** [comment] 2022-01-24 20:47
P.S.
Actually ShareX has a very dodgy implementation of the DIB format 😆 
https://github.com/ShareX/ShareX/blob/8c3dc0b78c6283551734ab3506db1f059ea7e91e/ShareX.HelpersLib/Helpers/ClipboardHelpersEx.cs#L69
"This is (wrongly) accepted by many applications as containing transparency, so I'm abusing it for that."

I'll check that statement... but it points out how broken the clipboard is.

**Comment by Lakritzator** [comment] 2022-01-24 21:22
Just collecting information here:

- https://medium.com/sysf/bits-to-bitmaps-a-simple-walkthrough-of-bmp-image-format-765dc6857393 A nice article on DIB / BMP and pointing for 32 bit (24 bit + alpha) to the following article.
- https://en.wikipedia.org/wiki/BMP_file_format#Pixel_storage

**Comment by Lakritzator** [comment] 2022-01-24 21:34
I just noticed that this was closed, which I didn't... reopening as the issue is still recent and being worked on

**Comment by Lakritzator** [comment] 2022-01-25 11:40
I've added a workaround for this issue to Greenshot 1.3.229, with the hope I find a better way or Microsoft (or Docker?) finally fixes this. You can download it here: https://github.com/greenshot/greenshot/releases

**Comment by Jaex** [comment] 2022-01-25 13:24
> Btw. maybe a nice fact, ShareX shared a lot of code from Greenshot.

Hi Robin, I just wanted to mention that in 2016 we added annotation support to our region capture along with an option to use it instead of the Greenshot image editor. In 2017 we enabled this by default and Greenshot editor was only usable through an advanced setting. In 2018 we completely removed Greenshot editor library reference and now using our own image editor exclusively which has zero code from Greenshot editor and works pretty differently, because it is actually windowed region capture acting like image editor. So we don't actually use/share any codes from Greenshot for long time.

Sorry for this off-topic reply but I couldn't find any direct way to reach you. Last time I reached you was when we were using SourceForge, using their dm system. :)

**Comment by Lakritzator** [comment] 2022-01-25 14:02
> > Btw. maybe a nice fact, ShareX shared a lot of code from Greenshot.
> 
> Hi Robin, I just wanted to mention that in 2016 we added annotation support to our region capture along with an option to use it instead of the Greenshot image editor. In 2017 we enabled this by default and Greenshot editor was only usable through an advanced setting. In 2018 we completely removed Greenshot editor library reference and now using our own image editor exclusively which has zero code from Greenshot editor and works pretty differently, because it is actually windowed region capture acting like image editor. So we don't actually use/share any codes from Greenshot for long time.
> 
> Sorry for this off-topic reply but I couldn't find any direct way to reach you. Last time I reached you was when we were using SourceForge, using their dm system. :)

Hi @Jaex, no problem and I was aware (read it recently). It sometimes does help that someone doesn't have a certain issue with ShareX, so I can compare the code 😉  The usage of the DIB clipboard format was interesting, but I really need to do a bit of testing with the impact. I hate the clipboard, some time ago I even started working on an application just for that but never got around to continue working on it: https://github.com/dapplo/Dapplo.Dopy

**Comment by Lakritzator** [comment] 2022-02-01 21:53
I've done some research, I actually found the code that ShareX also uses, and converted it to work with Greenshot.
This is available in 1.3.235, which can be found here: https://github.com/greenshot/greenshot/releases

I'd love to know if that fixes the issue, if you used 1.3.229 please do check if only the formats "Device Independent Bitmap" and "PNG" are selected in the advanced settings, if not make that happen (disable "Bitmap").

**Comment by Jaex** [comment] 2022-02-02 03:17
@Lakritzator are you using Discord? I thought that I could add you to my friends list, so when needed we could talk.

**Comment by Lakritzator** [comment] 2022-02-02 07:54
> @Lakritzator are you using [Discord](https://discord.com)? I thought that I could add you to my friends list, so when needed we could talk.

Yes, but so little... it's only something I use one day a week and only to have a voice session with some people. I'm not active there, in fact I'm not a big social media fan. But you can find me on twitter (@Lakritzator ) or on LinkedIn (look for my name).

**Comment by schuettecarsten** [comment] 2022-02-02 12:03
> I'd love to know if that fixes the issue, if you used 1.3.229 please do check if only the formats "Device Independent Bitmap" and "PNG" are selected in the advanced settings, if not make that happen (disable "Bitmap").

I have set the image formats to "Device Independent Bitmap" and "PNG" only (is that the default setting?) and can confirm that there is no more flickering with version 1.3.235. Thank you very much!

**Comment by Lakritzator** [comment] 2022-02-02 14:52
@schuettecarsten Thanks for testing this, yes those settings are the default, this is why it was important to confirm that these settings are used so I know if the default which was causing issues, now no longer causes issues.

That it no longer flickers is great news, it does make my opinion on the clipboard a lot worse (and it was already not so good).
To be clear, I even worked (it's on hold) on a clipboard tool: https://github.com/dapplo/Dapplo.Dopy

Anyway I will take the current implementation of the fix, which is slightly dirty, and improve on it, it seems so many clipboard operations are made, it pays off to make it use as little resources as possible. 😉

**Comment by schuettecarsten** [comment] 2022-02-04 10:21
When using Greenshot 3.2.325 and clipboard format "DIB" and "PNG", it is not possible to paste a screenshot from Clipboard into Microsoft Teams chat. I am unsure if this is caused by the DIB changes or something else, but I am sure that it worked in the past.

**Comment by Lakritzator** [comment] 2022-02-06 21:54
I had a look at this, it must be the format change. I will have a further detailed look at it, but to be honest MS Teams should just take the PNG format, would be so much easier!!

As a workaround, active Windows Bitmap as a format in the expert settings.

**Comment by Lakritzator** [comment] 2022-02-08 15:51
I actually found what caused it, my mistake... The installer didn't provide some additional .dll files we needed, thus the new code didn't run. This is now fixed, please test 1.3.239 or later but do reset the settings back to before (Device Independent Bitmap & PNG)

1.3.239 (or newer) can be found [here](https://github.com/greenshot/greenshot/releases)

**Comment by schuettecarsten** [comment] 2022-02-09 07:48
Yeah, now Teams (and WhatsApp) work with PNG+DIB mode and without Windows Bitmap. Thank you!

**Comment by Lakritzator** [comment] 2022-02-09 08:13
Recap: Somehow Windows 11 and / or Docker (or maybe WSL) doesn't like the DIB (which is a .bmp without file header) which Greenshot created, and causes some weird UI glitches. Sometimes more sometimes less.
The format also crashes VirtualBox, as was reported in [BUG-2892](https://greenshot.atlassian.net/browse/BUG-2892)

We changed the DIB format, created it manually and using a different configuration, this seems to be accepted so far by "all" applications and not crash VirtualBox or cause Windows 11 UI issues.

Closing this.

**Closed by Lakritzator** 2022-02-09 08:13 UTC
Labels: bug

**Comment by apos** [comment] 2022-04-26 09:18
> I have set the image formats to "Device Independent Bitmap" and "PNG" only (is that the default setting?) and can confirm that there is no more flickering with version 1.3.235. Thank you very much!

In my case (Windows 11 - Greenshot 1.2.10.6 - Stable), I have to use **only PNG.** "Device Indepentent Bitmap" causes the Issue.

**Comment by Lakritzator** [comment] 2022-04-26 19:46
@apos Yeah, the fix is in the not released 1.3 Greenshot versions, which can be found here: https://github.com/greenshot/greenshot/releases

If you are happy with ShareX, then that is good for you, use what you like.

**Comment by badabing2005** [comment] 2022-04-26 21:24
ShareX is good but not great, see my comments [here](https://github.com/ShareX/ShareX/issues/6044) which totally went unanswered.
I really like the dynamic capture selection (whatever it is called, the one that selects widgets based on where you are hovering)
I'm currently using a hybrid of ShareX with Greenshot,
I let ShareX take the screenshot, and with Action it opens it in Greenshot editor which I love.
There is a delay, but it works, it's not perfect, I still don't get the nice naming functionality of Greenshot.

**Comment by apos** [comment] 2022-04-29 05:28
> ShareX is good but not great, see my comments [here](https://github.com/ShareX/ShareX/issues/6044) which totally went unanswered.

After thorough testing: you got me back with the beta version of Greenshot from ShareX :-) Greenshot has a much more cleaner UI. And I can confirn, that in 1.2.349 the error is gone. No more flickering. Expert Settings to "PNG" and "Device Independent Bitmap" which is necessary. If "Device Independent Bitmap" is not set, you cannot copy and paste to third party apps.

Good work. Cheers.

**Comment by JTerry7** [comment] 2022-06-01 18:25
I get this flickering and I have the latest stable version which is 1.2.10.  I guess the only solution is to use another screen capture software?

**Comment by MitchTalmadge** [comment] 2022-06-15 08:02
The underlying cause was WSLg crashing and restarting in an endless loop: https://github.com/microsoft/wslg/issues/443

Updating to WSLg 1.0.34 has solved this problem for me. In an elevated prompt:

```
(base) PS C:\Users\mitch> wsl --update
Installing: Windows Subsystem for Linux
Windows Subsystem for Linux has been installed.

(base) PS C:\Users\mitch> wsl --version
WSL version: 0.60.0.0
Kernel version: 5.10.102.1
WSLg version: 1.0.34
MSRDC version: 1.2.2924
Direct3D version: 1.601.0
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.160
```

**Comment by luciandf** [comment] 2022-07-20 08:53
> When using Greenshot 1.3.325 and clipboard format "DIB" and "PNG", it is not possible to paste a screenshot from Clipboard into Microsoft Teams chat. I am unsure if this is caused by the DIB changes or something else, but I am sure that it worked in the past.

I have tried this fix too and noticed I cannot paste the screenshot in an email but then I pressed WinKey+V to bring up the clipboard history and I saw that there was another empty entry after the copied screenshot. I selected the entry with the screenshot and it was pasted in the email no problem. So maybe try that?

**Comment by luciandf** [comment] 2022-07-20 09:00
> The underlying cause was Weston, part of WSLg, crashing and restarting in an endless loop: [microsoft/wslg#443](https://github.com/microsoft/wslg/issues/443)
> 
> Updating to WSLg 1.0.34 has solved this problem for me. In an elevated prompt:
> 
> ```
> (base) PS C:\Users\mitch> wsl --update
> Installing: Windows Subsystem for Linux
> Windows Subsystem for Linux has been installed.
> 
> (base) PS C:\Users\mitch> wsl --version
> WSL version: 0.60.0.0
> Kernel version: 5.10.102.1
> WSLg version: 1.0.34
> MSRDC version: 1.2.2924
> Direct3D version: 1.601.0
> DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
> Windows version: 10.0.22621.160
> ```
> 
> You may need to [install the WSL preview](https://aka.ms/wslstorepage) to get this version if it hasn't been released when reading this.

On my sistem `--version` is not an option for `wsl`. How do you find the wsl version exactly?

**Comment by scarolan** [comment] 2022-08-04 19:49
Dear god this is annoying.  why was this issue closed?  I can barely type this because of the screen flicker

**Comment by luciandf** [comment] 2022-08-04 19:51
> Dear god this is annoying. why was this issue closed? I can barely type this because of the screen flicker

I have already uninstalled the program until this issue will be fixed.

**Comment by scarolan** [comment] 2022-08-04 19:51
ok i can see that it's a WSL issue now.  sorry for the ragepost.  I guess I'll wait for a stable version of WSL to fix this, in the meantime I'm going back to lightshot

**Comment by bellicapax** [comment] 2022-08-18 23:41
> > The underlying cause was Weston, part of WSLg, crashing and restarting in an endless loop: [microsoft/wslg#443](https://github.com/microsoft/wslg/issues/443)
> > Updating to WSLg 1.0.34 has solved this problem for me. In an elevated prompt:
> > ```
> > (base) PS C:\Users\mitch> wsl --update
> > Installing: Windows Subsystem for Linux
> > Windows Subsystem for Linux has been installed.
> > 
> > (base) PS C:\Users\mitch> wsl --version
> > WSL version: 0.60.0.0
> > Kernel version: 5.10.102.1
> > WSLg version: 1.0.34
> > MSRDC version: 1.2.2924
> > Direct3D version: 1.601.0
> > DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
> > Windows version: 10.0.22621.160
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You may need to [install the WSL preview](https://aka.ms/wslstorepage) to get this version if it hasn't been released when reading this.
> 
> On my sistem `--version` is not an option for `wsl`. How do you find the wsl version exactly?

I ran into this same issue. It seems by installing wsl via terminal (not the Microsoft Store), I had an out-of-date version of WSL. Following the link in [this comment ](https://github.com/microsoft/wslg/issues/443#issuecomment-1210962218)and installing from the store upgraded my wsl to where `--version` was a valid flag and also fixed the flickering issue.

**Comment by Griefed** [comment] 2023-09-17 12:31
> This happens to me too on Windows 11. I do not have Docker Desktop installed, but I do have WSL and probably docker engine. I have also confirmed that simply copying some plain text into the clipboard resolves the issue.
> 
> Edit: I was still using the most "recent" stable build. I have updated to the latest unstable and will see if it is resolved.

Same here. I can confirm that using [v1.3.277](https://github.com/greenshot/greenshot/releases/tag/v1.3.277) resolved this issue for me. No more WSL CPU load after taking a screencap using Greenshot. WSL and Docker are behaving nicely now. :)

Cheers,
Griefed
