### ISSUE TITLE
Capture window does not snap to windows

### ISSUE THREAD

**Issue by ScribbleGhost** [greenshot/greenshot#354] opened 2021-12-19 12:14 UTC
**Describe the bug**
Greenshot will not _snap to windows_ when choosing "Capture window" <kbd>Alt</kbd>+<kbd>Prntscrn</kbd>. The green overlay appears as it normally does, but it does not snap to any window on the desktop.

A workaround is to use "Capture window from list", but this is limited because it does not allow to capture popup windows from for example device manager.

**To Reproduce**
Example steps to reproduce the behavior:
1. Start Greenshot with factory settings.
2. Right click on the Greenshot system tray and choose Capture window.
3. Try to move the cursor over a window and see if it snaps to the window border.

**Expected behavior**
What should happen is that the green overlay snaps to the window for which you have your cursor over.

**Screenshots**

https://user-images.githubusercontent.com/49068170/146674446-c15a4368-604b-4081-990e-4de1812bd290.mp4

**Versions (please complete the following information):**
 - Greenshot version 1.2.10 Build 6 (64 bit)
 - Windows version 10, 21H2

**Additional context**
Note that this started happening in Windows 21H1 but the same problem persists in 21H2.
I have the same problem with Snagit so it seems something have either changed in Windows or there must be something wrong with my computer. I will try to check on another computer and report back.

**Comment by ScribbleGhost** [comment] 2021-12-19 12:18
Just found out that the green overlay will snap to the taskbar and individual parts of the taskbar, for example the clock, system trays or the start button, but it sees the desktop as one whole window. That is, it does not differentiate between the windows on the desktop.

**Comment by natlose** [comment] 2022-01-17 10:08
I confirm, also have the issue on W10Pro 21H2, same Greenshot version as above.

**Comment by Lakritzator** [comment] 2022-01-17 22:31
I found an issue with figuring out what windows are visible and what not, this was fixed in one of our newer builds.
Unfortunately these have not been released, but you can already try them out.
If you can, mainly to confirm if the issue is solved, please try out the "unstable" 1.3 from here: https://github.com/greenshot/greenshot/releases
(You might need to convince your browser to keep the file, and windows to install it, as the code signing is still missing)

**Comment by natlose** [comment] 2022-01-19 15:58
Strange...
I tried the 1.3 unstable version.
I had to run it from source, as the pre-built application was banned by Defender Smart Screen.
The fresh compiled application crashed silently to death.
The crash occured during `Greenshot.Base.Core.EnvironmentInfo.GetGreenshotVersion` method.
In the statement
```
if (!string.IsNullOrEmpty(assemblyFileVersionAttribute?.Version))
            {
                var assemblyFileVersion = new Version(assemblyFileVersionAttribute.Version);
                greenshotVersion = assemblyFileVersion.ToString(3);
            }
```
the `ToString()` accepts only values 0, 1, 2, so it threw an `ArgumentException`.
I managed to run the appliaction with an argument 2, and voilà: _**the Capture Window function works!**_
BUT
I made a crosscheck, and gave a try again for the former version. Strange enough, the Capture Window function _**now works also in 1.2.10 version**_.

**Comment by Lakritzator** [comment] 2022-01-23 00:10
I think the error you were seeing with the "ToString(3)" might have been an issue with how you got the sources.
It should have worked, as the version is 1.3.222, which has 3 items.

Also, you should still be able to download the latest builds, even if they are not signed yet.
You will need to click "keep" in some sub window of the download screen.
But this is how we managed to save it ourselves when testing.

**Comment by Lakritzator** [comment] 2022-02-02 12:58
@ScribbleGhost Can you try the latest builds of Greenshot, so I know if you issue is solved?
https://github.com/greenshot/greenshot/releases

**Comment by Alakarr** [comment] 2022-03-18 02:15
> @ScribbleGhost Can you try the latest builds of Greenshot, so I know if your issue is solved? https://github.com/greenshot/greenshot/releases

I was having the same issue as @ScribbleGhost. I installed Greenshot 1.3.239 unstable and the issue seems to be resolved. Can capture a window with Alt - Prtscr or using the right click menu. Using Windows 10 Pro 21H2.

**Comment by Lakritzator** [comment] 2022-03-18 07:09
@Alakarr thanks for the feedback, as I didn't hear anything other, I will close it with "works in the latest 1.3".

**Closed by Lakritzator** 2022-03-18 07:09 UTC
Labels: Awaiting feedback
