### ISSUE TITLE
Greenshot 1.3 does not copy to clipboard

### ISSUE THREAD

**Issue by c400ru** [greenshot/greenshot#374] opened 2022-02-07 12:53 UTC
This GitHub repository is for developers, if you want to report a bug for Greenshot as a user please do so in our JIRA issue system here: https://greenshot.atlassian.net/projects/BUGS/issues/filter=allopenissues

**Describe the bug**

**To Reproduce**

0. Press Print Screen
1. Copy To clipboard

**Expected behavior**

**Versions (please complete the following information):**
 - Greenshot-INSTALLER-1.3.234-UNSTABLE was last working. All after does not copy to clipboard
 - Windows 10 x64 19044.1503

**Comment by Lakritzator** [comment] 2022-02-07 13:53
Greenshot 1.3.234 definitively copies to the clipboard, so please let me know why you assume it doesn't.

**Comment by c400ru** [comment] 2022-02-07 15:48
Greenshot-INSTALLER-1.3.234-UNSTABLE works great
v1.3.238, v1.3.235 does not. tried on my PC.

**Comment by Lakritzator** [comment] 2022-02-07 19:50
I know when I made the change, it's for #348, but to which application do you try to paste?

**Comment by c400ru** [comment] 2022-02-07 23:34
whatsapp

**Comment by drdiablo1337** [comment] 2022-02-08 07:23
I have the same problem with version v1.3.238.
No matter what is photographed, the clipboard is not filled. The same can also be reproduced in the Greenshot editor, copying to the clipboard is not possible here either

**Comment by mischlrebl** [comment] 2022-02-08 10:24
same with 1.3.238, before with 1.3.235 and even before with a version - where I thought the problem is sitting in front of the pc.

copy neither works from the destination picker nor the editor, where the export text is shown in the footer.

here what is written to the log:
1. copy via destination picker
2. copy in an (already) open editor window

2022-02-08 11:22:46,665 [Greenshot] INFO  - [Greenshot.Base.Controls.GreenshotForm] Form was closed with OK: storing field values.
2022-02-08 11:22:46,674 [Greenshot] INFO  - [Greenshot.Helpers.CaptureHelper] Calling processor TitleFix
2022-02-08 11:22:46,674 [Greenshot] INFO  - [Greenshot.Helpers.CaptureHelper] Calling processor Windows10OcrProcessor
2022-02-08 11:22:49,992 [Greenshot] ERROR - [Greenshot.Base.Core.ClipboardHelper] Error creating DIB for the Clipboard.
System.IO.FileNotFoundException: Die Datei oder Assembly "System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
File name: 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Greenshot.Base.Core.DibHelper.ConvertToDib(Bitmap sourceBitmap)
   at Greenshot.Base.Core.ClipboardHelper.SetClipboardData(ISurface surface) in D:\a\1\s\src\Greenshot.Base\Core\ClipboardHelper.cs:line 869

WRN: Protokollierung der Assemblybindung ist AUS.
Sie können die Protokollierung der Assemblybindungsfehler aktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) auf 1 festlegen.
Hinweis: Die Protokollierung der Assemblybindungsfehler führt zu einer gewissen Leistungseinbuße.
Sie können dieses Feature deaktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] entfernen.

2022-02-08 11:22:50,010 [Greenshot] INFO  - [Greenshot.Base.Core.AbstractDestination] Export to Copy to clipboard success, closing menu
2022-02-08 11:23:07,549 [Greenshot] ERROR - [Greenshot.Base.Core.ClipboardHelper] Error creating DIB for the Clipboard.
System.IO.FileNotFoundException: Die Datei oder Assembly "System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
File name: 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Greenshot.Base.Core.DibHelper.ConvertToDib(Bitmap sourceBitmap)
   at Greenshot.Base.Core.ClipboardHelper.SetClipboardData(ISurface surface) in D:\a\1\s\src\Greenshot.Base\Core\ClipboardHelper.cs:line 869

WRN: Protokollierung der Assemblybindung ist AUS.
Sie können die Protokollierung der Assemblybindungsfehler aktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) auf 1 festlegen.
Hinweis: Die Protokollierung der Assemblybindungsfehler führt zu einer gewissen Leistungseinbuße.
Sie können dieses Feature deaktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] entfernen.

**Comment by mischlrebl** [comment] 2022-02-08 10:26
the 'workaround' from ISSUE-372 does the trick, even on the already opened editor

**Comment by drdiablo1337** [comment] 2022-02-08 11:14
> the 'workaround' from #372 does the trick, even on the already opened editor ![image](https://user-images.githubusercontent.com/28529799/152968920-d711839d-0d0a-431d-aac3-8cdcea01a279.png)

The workaround worked :)

**Comment by Lakritzator** [comment] 2022-02-08 12:32
@mischlrebl damn, I was totally blind for the fact that there might be an error in the installer!!!
Thanks for directing my attention to the logs, I feel a bit stupid now.

That I can probably fix that.

**Comment by c400ru** [comment] 2022-02-08 13:13
Btw, installer does not work without admin rights. Please make user rights requirement for the installer.
1.2 was correct

Отправлено с iPhone

**Comment by Lakritzator** [comment] 2022-02-08 13:14
I was so convinced I didn't make mistakes in my code, that I forgot to check the installation files.
Due to some new logic, I needed to add a few dll files, thus causing issues in that area.

I fixed this, please @drdiablo1337, @c400ru test but do reset the settings back to before (Device Independent Bitmap & PNG)  1.3.239 found [here](https://github.com/greenshot/greenshot/releases)

**Comment by Lakritzator** [comment] 2022-02-08 13:14
@c400ru 

> Btw, installer does not work without admin rights. Please make user rights requirement for the installer. 1.2 was correct 

If possible, log another issue with the details, otherwise things get out of order.
I need some more details, as "it works fine for me".

**Comment by mischlrebl** [comment] 2022-02-08 13:33
1.3.239: copy works as expected from destination picker as well editor (with DIB disabled)

**Comment by Lakritzator** [comment] 2022-02-08 13:39
> 1.3.239: copy works as expected from destination picker as well editor (with DIB disabled)

Just checking, you mean DIB enabled? You will need to have the first option "Device Independent Bitmap" and "PNG" active, no others. I tested it with MS Teams, works as it should (so far, not tested transparency yet)

**Comment by mischlrebl** [comment] 2022-02-08 13:52
sorry for the confusion.
correct: DIB and PNG enabled, Windows Bitmap disabled again

**Comment by Lakritzator** [comment] 2022-02-08 13:59
Anyone against closing this? Especially @c400ru as you reported it?

**Comment by Lakritzator** [comment] 2022-02-08 15:51
Closing this, sorry for the mistake from my side, I almost believed I've added a new clipboard format which wasn't accepted. If only I would have seen the error that @mischlrebl saw... Anyway, this "should" still solve #348 (but I will follow it there)

**Closed by Lakritzator** 2022-02-08 15:51 UTC
Labels: bug, Awaiting feedback

**Comment by Lakritzator** [comment] 2022-03-23 21:03
Try 246: https://github.com/greenshot/greenshot/releases
