### ISSUE TITLE
OverflowException when trying to move a line in the editor

### ISSUE THREAD

**Issue by mischlrebl** [greenshot/greenshot#246] opened 2020-08-19 09:04 UTC
I was trying to move a line in the editor - with tho image elements - and the got this:

Software version: 1.3.116 - 133438ab55 (64 bit)
.NET runtime version: 4.0.30319.42000+
Time: 2020-08-19 06:36:10 +02:00
OS: Windows 10 2004 x64 build 19041
GDI object count: 81
User object count: 76

Exception: System.OverflowException
Message: Overflow error.

Stack:
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawLine(Pen pen, Int32 x1, Int32 y1, Int32 x2, Int32 y2)
   at Greenshot.Drawing.LineContainer.Draw(Graphics graphics, RenderMode rm) in D:\a\1\s\Greenshot\Drawing\LineContainer.cs:line 90
   at Greenshot.Drawing.DrawableContainer.DrawContent(Graphics graphics, Bitmap bmp, RenderMode renderMode, Rectangle clipRectangle) in D:\a\1\s\Greenshot\Drawing\DrawableContainer.cs:line 367
   at Greenshot.Drawing.DrawableContainerList.Draw(Graphics g, Bitmap bitmap, RenderMode renderMode, Rectangle clipRectangle) in D:\a\1\s\Greenshot\Drawing\DrawableContainerList.cs:line 274
   at Greenshot.Drawing.Surface.SurfacePaint(Object sender, PaintEventArgs paintEventArgs) in D:\a\1\s\Greenshot\Drawing\Surface.cs:line 1527
   at System.Windows.Forms.Control.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Configuration dump:

and this view:
![image](https://user-images.githubusercontent.com/28529799/90614968-b062bd00-e20b-11ea-9c39-894743179abc.png)

Undo was available but no effect.

not reproducable atm

**Comment by jklingen** [comment] 2021-02-28 17:51
I couldn't reproduce this, but I have been investigating a bit. Obviously these errors do occur when drawing waaaaay out of screen bounds, which normally shouldn't happen when dragging elements around in the editor. Someone in JIRA mentioned this happens when resizing lines while holding down the shift key.

So I played a bit with our scale-keeping-aspect-ratio feature and noticed that it behaves a bit strange in some situations, resulting e.g. in an extremely wide/high element. My theory is that this causes the issue. @mischlrebl any chance you unintentionally shift-grabbed a line by one of its handles while this happened (instead of dragging all the selected elements?)

E.g. if you draw a nearly-horizontal line (the **right end just slightly above** the left one), then hold down shift while dragging the **left** handle up or down, you can watch the line grow very long very quickly, while the editor tries to keep the line's aspect ratio (i.e. angle). 
The behavior of that feature is weird and inconsistent and should be fixed. My hope is that this also fixes the error, as I don't have any other idea right now why this should be happening. Didn't have time to implement that fix yet, though.

**Comment by mischlrebl** [comment] 2021-03-04 07:25
Thank you for the investigations and explanations.

Unfortunately I am not longer able to remember what causes the error half a year ago.

Indeed, I am really often work which Shift-line variations to align lines so this happened intentionally for sure.
Playing around there are different problems that causes an error, but it seems only when editing a line, but not while inserting it.

A fix would be great for sure!

**Closed** 2021-03-27 18:54 UTC
Labels: bug

**Comment by jklingen** [comment] 2021-03-28 14:00
This issue should be fixed in Greenshot 1.3. The final release is not ready yet, but if you don't want to wait, you can try the latest unstable build (>= 1.3.178) from the [Greenshot version history page](https://getgreenshot.org/version-history/) or from the [Github releases page](https://github.com/greenshot/greenshot/releases).

**Comment by mischlrebl** [comment] 2021-03-31 12:00
Thank you. 
I'am always using the latest version and it looks good - could not find any problems so far
